/*
Navicat MySQL Data Transfer

Source Server         : 172.20.53.202
Source Server Version : 50723
Source Host           : 172.20.53.202:3306
Source Database       : base_walsin_,mysql

Target Server Type    : ORACLE
Target Server Version : 110100
File Encoding         : 65001

Date: 2018-12-10 17:57:20
*/

;

-- ----------------------------
-- Table structure for IUAPD_ALLOWANCES
-- ----------------------------
DROP TABLE IUAPD_ALLOWANCES;
CREATE TABLE IUAPD_ALLOWANCES (
ID VARCHAR2(64) NOT NULL ,
CODE VARCHAR2(64) NULL ,
NAME VARCHAR2(64) NULL ,
SEX NUMBER(11) NULL ,
DEPT VARCHAR2(64) NULL ,
LEVEL VARCHAR2(64) NULL ,
SERVICE_YEARS NUMBER NULL ,
SERVICE_YEARS_COMPANY NUMBER NULL ,
YEAR VARCHAR2(64) NULL ,
MONTH NUMBER NULL ,
ALLOWANCE_TYPE NUMBER NULL ,
ALLOWANCE_STANDARD NUMBER NULL ,
ALLOWANCE_ACTUAL NUMBER NULL ,
EXDEEDS NUMBER(11) NULL ,
APPLY_TIME VARCHAR2(64) NULL ,
PICK_TYPE NUMBER(11) NULL ,
PICK_TIME VARCHAR2(64) NULL ,
REMARK VARCHAR2(200) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_ALLOWANCES.ID IS '单据Id';
COMMENT ON COLUMN IUAPD_ALLOWANCES.CODE IS '员工编号';
COMMENT ON COLUMN IUAPD_ALLOWANCES.NAME IS '员工姓名';
COMMENT ON COLUMN IUAPD_ALLOWANCES.SEX IS '员工性别';
COMMENT ON COLUMN IUAPD_ALLOWANCES.DEPT IS '所属部门 -部门表Id';
COMMENT ON COLUMN IUAPD_ALLOWANCES.LEVEL IS '职级';
COMMENT ON COLUMN IUAPD_ALLOWANCES.SERVICE_YEARS IS '工龄';
COMMENT ON COLUMN IUAPD_ALLOWANCES.SERVICE_YEARS_COMPANY IS '司龄';
COMMENT ON COLUMN IUAPD_ALLOWANCES.YEAR IS '年份';
COMMENT ON COLUMN IUAPD_ALLOWANCES.MONTH IS '月份';
COMMENT ON COLUMN IUAPD_ALLOWANCES.ALLOWANCE_TYPE IS '补贴类别';
COMMENT ON COLUMN IUAPD_ALLOWANCES.ALLOWANCE_STANDARD IS '补贴标准';
COMMENT ON COLUMN IUAPD_ALLOWANCES.ALLOWANCE_ACTUAL IS '实际补贴';
COMMENT ON COLUMN IUAPD_ALLOWANCES.EXDEEDS IS '是否超标  1.超标，0.未超标 --枚举';
COMMENT ON COLUMN IUAPD_ALLOWANCES.APPLY_TIME IS '申请时间';
COMMENT ON COLUMN IUAPD_ALLOWANCES.PICK_TYPE IS '领取方式  1.转账，2.现金 --枚举';
COMMENT ON COLUMN IUAPD_ALLOWANCES.PICK_TIME IS '领取时间';

-- ----------------------------
-- Records of IUAPD_ALLOWANCES
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_EMERGENCY_CONTACT
-- ----------------------------
DROP TABLE IUAPD_EMERGENCY_CONTACT;
CREATE TABLE IUAPD_EMERGENCY_CONTACT (
ID VARCHAR2(64) NOT NULL ,
PASSENGER_ID VARCHAR2(64) NULL ,
CONTACT_NAME VARCHAR2(32) NULL ,
CONTACT_PHONE VARCHAR2(32) NULL ,
CONTACT_RELATION VARCHAR2(64) NULL ,
REMARK VARCHAR2(255) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_EMERGENCY_CONTACT.PASSENGER_ID IS '员工编号';
COMMENT ON COLUMN IUAPD_EMERGENCY_CONTACT.CONTACT_NAME IS '联系人姓名';
COMMENT ON COLUMN IUAPD_EMERGENCY_CONTACT.CONTACT_PHONE IS '联系人电话';
COMMENT ON COLUMN IUAPD_EMERGENCY_CONTACT.CONTACT_RELATION IS '与联系人关系 ';

-- ----------------------------
-- Records of IUAPD_EMERGENCY_CONTACT
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_GRID_TEMP
-- ----------------------------
DROP TABLE IUAPD_GRID_TEMP;
CREATE TABLE IUAPD_GRID_TEMP (
ID VARCHAR2(64) NOT NULL ,
MODEL_CODE VARCHAR2(255) NULL ,
MODEL_NAME VARCHAR2(255) NULL ,
MODEL_TYPE VARCHAR2(255) NULL ,
MODEL_CONTENT NCLOB NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_GRID_TEMP.ID IS '主键';
COMMENT ON COLUMN IUAPD_GRID_TEMP.MODEL_CODE IS '模型编码';
COMMENT ON COLUMN IUAPD_GRID_TEMP.MODEL_NAME IS '模型名称';
COMMENT ON COLUMN IUAPD_GRID_TEMP.MODEL_TYPE IS '模型类型';

-- ----------------------------
-- Records of IUAPD_GRID_TEMP
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_PASSENGER
-- ----------------------------
DROP TABLE IUAPD_PASSENGER;
CREATE TABLE IUAPD_PASSENGER (
ID VARCHAR2(64) NOT NULL ,
CODE VARCHAR2(64) NOT NULL ,
NAME VARCHAR2(64) NULL ,
SEX NUMBER NULL ,
DEPT VARCHAR2(64) NULL ,
PHONE VARCHAR2(30) NULL ,
IS_VIP NUMBER NULL ,
GRADE NUMBER NULL ,
EXPIRATION_DATE VARCHAR2(255) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_PASSENGER.CODE IS '员工编号';
COMMENT ON COLUMN IUAPD_PASSENGER.NAME IS '员工姓名';
COMMENT ON COLUMN IUAPD_PASSENGER.SEX IS '员工性别 2.男，1.女';
COMMENT ON COLUMN IUAPD_PASSENGER.DEPT IS '所属部门';
COMMENT ON COLUMN IUAPD_PASSENGER.PHONE IS '手机号';
COMMENT ON COLUMN IUAPD_PASSENGER.IS_VIP IS '是否会员 2表示是，1表示否，默认1';
COMMENT ON COLUMN IUAPD_PASSENGER.GRADE IS '会员等级 默认0是非会员，会员1,2,3,4,5（从低到高）';
COMMENT ON COLUMN IUAPD_PASSENGER.EXPIRATION_DATE IS '会员到期日期';

-- ----------------------------
-- Records of IUAPD_PASSENGER
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_PURCHASE_ORDER
-- ----------------------------
DROP TABLE IUAPD_PURCHASE_ORDER;
CREATE TABLE IUAPD_PURCHASE_ORDER (
ID VARCHAR2(64) NOT NULL ,
ORDER_CODE VARCHAR2(64) NULL ,
ORDER_NAME VARCHAR2(64) NULL ,
ORDER_TYPE NUMBER(11) NULL ,
ORDER_PRICE NUMBER NULL ,
ORDER_USER VARCHAR2(64) NULL ,
ORDER_DEPT VARCHAR2(64) NULL ,
ORDER_DATE VARCHAR2(64) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ID IS '请购单主键id';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ORDER_CODE IS '请购单编号';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ORDER_NAME IS '请购单名称';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ORDER_TYPE IS '请购单类型 1.普通采购，2委托代销，3直运采购';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ORDER_PRICE IS '请购单价格';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ORDER_USER IS '请购单申请人';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ORDER_DEPT IS '请购单申请部门';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER.ORDER_DATE IS '请购单申请日期';

-- ----------------------------
-- Records of IUAPD_PURCHASE_ORDER
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_PURCHASE_ORDER_DETAIL
-- ----------------------------
DROP TABLE IUAPD_PURCHASE_ORDER_DETAIL;
CREATE TABLE IUAPD_PURCHASE_ORDER_DETAIL (
ID VARCHAR2(64) NOT NULL ,
ORDER_ID VARCHAR2(64) NULL ,
DETAIL_NAME VARCHAR2(64) NULL ,
DETAIL_MODEL VARCHAR2(64) NULL ,
DETAIL_COUNT NUMBER(11) NULL ,
DETAIL_DATE VARCHAR2(64) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER_DETAIL.ORDER_ID IS '请购单ID';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER_DETAIL.DETAIL_NAME IS '物料名称';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER_DETAIL.DETAIL_MODEL IS '物料型号 自定义参照';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER_DETAIL.DETAIL_COUNT IS '物料数量';
COMMENT ON COLUMN IUAPD_PURCHASE_ORDER_DETAIL.DETAIL_DATE IS '需求日期';

-- ----------------------------
-- Records of IUAPD_PURCHASE_ORDER_DETAIL
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_RANKS
-- ----------------------------
DROP TABLE IUAPD_RANKS;
CREATE TABLE IUAPD_RANKS (
ID VARCHAR2(64) NOT NULL ,
CODE VARCHAR2(255) NULL ,
TYPE VARCHAR2(255) NULL ,
GRADE NUMBER NULL ,
LEVEL VARCHAR2(255) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_RANKS.ID IS '职级Id';
COMMENT ON COLUMN IUAPD_RANKS.CODE IS '职级编码';
COMMENT ON COLUMN IUAPD_RANKS.TYPE IS '职级类别 技术、管理';
COMMENT ON COLUMN IUAPD_RANKS.GRADE IS '等级 1、2、3……';
COMMENT ON COLUMN IUAPD_RANKS.LEVEL IS '级别 定性级别';

-- ----------------------------
-- Records of IUAPD_RANKS
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_TRAVELING_INFORMATION
-- ----------------------------
DROP TABLE IUAPD_TRAVELING_INFORMATION;
CREATE TABLE IUAPD_TRAVELING_INFORMATION (
ID VARCHAR2(64) NOT NULL ,
PASSENGER_ID VARCHAR2(64) NULL ,
LINE VARCHAR2(64) NULL ,
STATION_BEGIN VARCHAR2(64) NULL ,
STATION_END VARCHAR2(64) NULL ,
COST NUMBER NULL ,
PAY_STATUS NUMBER NULL ,
TRAVEL_TIME VARCHAR2(64) NULL ,
REMARK VARCHAR2(255) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_TRAVELING_INFORMATION.PASSENGER_ID IS '员工编号';
COMMENT ON COLUMN IUAPD_TRAVELING_INFORMATION.LINE IS '乘车线路';
COMMENT ON COLUMN IUAPD_TRAVELING_INFORMATION.STATION_BEGIN IS '上车站点';
COMMENT ON COLUMN IUAPD_TRAVELING_INFORMATION.STATION_END IS '下车站点';
COMMENT ON COLUMN IUAPD_TRAVELING_INFORMATION.COST IS '费用';
COMMENT ON COLUMN IUAPD_TRAVELING_INFORMATION.PAY_STATUS IS '支付状态 2表支付过，1没有';
COMMENT ON COLUMN IUAPD_TRAVELING_INFORMATION.REMARK IS '备注';

-- ----------------------------
-- Records of IUAPD_TRAVELING_INFORMATION
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_TREELIST
-- ----------------------------
DROP TABLE IUAPD_TREELIST;
CREATE TABLE IUAPD_TREELIST (
ID VARCHAR2(64) NOT NULL ,
NAME VARCHAR2(64) NULL ,
CODE VARCHAR2(64) NULL ,
IS_SON NUMBER NULL ,
PARENTID VARCHAR2(64) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_TREELIST.IS_SON IS '是否有子节点 1.没有 2有';

-- ----------------------------
-- Records of IUAPD_TREELIST
-- ----------------------------

-- ----------------------------
-- Table structure for IUAPD_TREELIST_DETAIL
-- ----------------------------
DROP TABLE IUAPD_TREELIST_DETAIL;
CREATE TABLE IUAPD_TREELIST_DETAIL (
ID VARCHAR2(64) NOT NULL ,
CODE VARCHAR2(64) NULL ,
NAME VARCHAR2(64) NULL ,
AGE NUMBER(11) NULL ,
SEX NUMBER(11) NULL ,
TREE_ID VARCHAR2(64) NULL ,
CREATE_TIME VARCHAR2(64) NULL ,
CREATE_USER VARCHAR2(64) NULL ,
LAST_MODIFIED VARCHAR2(64) NULL ,
LAST_MODIFY_USER VARCHAR2(64) NULL ,
TS VARCHAR2(64) NULL ,
DR NUMBER NULL ,
BPM_STATE NUMBER NULL ,
TENANT_ID VARCHAR2(64) NULL 
)

;
COMMENT ON COLUMN IUAPD_TREELIST_DETAIL.CODE IS '工号';
COMMENT ON COLUMN IUAPD_TREELIST_DETAIL.NAME IS '姓名';
COMMENT ON COLUMN IUAPD_TREELIST_DETAIL.AGE IS '年龄';
COMMENT ON COLUMN IUAPD_TREELIST_DETAIL.SEX IS '性别 1女 2男';
COMMENT ON COLUMN IUAPD_TREELIST_DETAIL.TREE_ID IS 'treeId';

-- ----------------------------
-- Records of IUAPD_TREELIST_DETAIL
-- ----------------------------

-- ----------------------------
-- Indexes structure for table IUAPD_TREELIST
-- ----------------------------
CREATE INDEX name
ON IUAPD_TREELIST (NAME );
